---
# tasks file for appserver
# Install Python and Flask
- name: Install Python 3
  apt:
    name: python3
    state: present
    update_cache: yes
  become: yes

- name: Install pip for Python 3
  apt:
    name: python3-pip
    state: present
  become: yes

- name: Install Flask using pip
  pip:
    name: flask
    state: present
  become: yes
